import "server-only";

import { createReadStream, createWriteStream } from "node:fs";
import { copyFile, mkdir, readFile, rename, rm, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { Readable } from "node:stream";
import { pipeline } from "node:stream/promises";

import { NextResponse } from "next/server";

import { env } from "@/lib/env";
import { imageSizeProblem, INPUT_IMAGE_LIMITS, sendSize } from "@/lib/generation-models";

/**
 * Local file storage for generated media.
 *
 * Provider URLs are not ours to keep (they can expire or be withdrawn), so a
 * finished generation is downloaded here and served through an authorised
 * route. Keys are generated by the server (`assets/<org>/<asset>.<ext>`), never
 * taken from a request, and are resolved strictly inside STORAGE_DIR.
 */

export const MAX_DOWNLOAD_BYTES = 300 * 1024 * 1024;

const MIME_BY_EXT: Record<string, string> = {
  ".mp4": "video/mp4",
  ".mov": "video/quicktime",
  ".webm": "video/webm",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".webp": "image/webp",
  ".pdf": "application/pdf",
  ".docx": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  ".xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  ".pptx": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
};

const EXT_BY_MIME: Record<string, string> = {
  "video/mp4": ".mp4",
  "video/quicktime": ".mov",
  "video/webm": ".webm",
  "image/png": ".png",
  "image/jpeg": ".jpg",
  "image/webp": ".webp",
};

function root(): string {
  return path.resolve(process.cwd(), env().STORAGE_DIR);
}

/** Resolves a storage key to a path, refusing anything that would escape the storage root. */
export function resolveKey(key: string): string {
  const base = root();
  const full = path.resolve(base, key);
  if (!full.startsWith(base + path.sep)) throw new Error("Storage key escapes the storage root");
  return full;
}

export function mimeFor(key: string): string {
  return MIME_BY_EXT[path.extname(key).toLowerCase()] ?? "application/octet-stream";
}

export function extensionFor(contentType: string | null, url: string, fallback: string): string {
  const fromType = contentType ? EXT_BY_MIME[contentType.split(";")[0]!.trim().toLowerCase()] : undefined;
  if (fromType) return fromType;
  try {
    const ext = path.extname(new URL(url).pathname).toLowerCase();
    if (MIME_BY_EXT[ext]) return ext === ".jpeg" ? ".jpg" : ext;
  } catch {
    /* not a URL we can read an extension from */
  }
  return fallback;
}

/**
 * Downloads `url` into storage under `keyWithoutExt` plus the right extension.
 * `sim://showcase/x.mp4` copies a bundled sample file (the generation simulator).
 */
export async function saveFromUrl(
  url: string,
  keyWithoutExt: string,
  fallbackExt: string,
): Promise<{ key: string; bytes: number; mimeType: string }> {
  if (url.startsWith("sim://")) {
    const rel = url.slice("sim://".length);
    const source = path.resolve(process.cwd(), "public", rel);
    if (!source.startsWith(path.resolve(process.cwd(), "public") + path.sep)) throw new Error("Bad simulator path");
    const key = keyWithoutExt + path.extname(source).toLowerCase();
    const target = resolveKey(key);
    await mkdir(path.dirname(target), { recursive: true });
    await copyFile(source, target);
    const { size } = await stat(target);
    return { key, bytes: size, mimeType: mimeFor(key) };
  }

  const res = await fetch(url, { signal: AbortSignal.timeout(5 * 60_000) });
  if (!res.ok || !res.body) throw new Error(`Download failed with HTTP ${res.status}`);
  const declared = Number(res.headers.get("content-length") ?? 0);
  if (declared > MAX_DOWNLOAD_BYTES) throw new Error("The generated file is larger than allowed");

  const key = keyWithoutExt + extensionFor(res.headers.get("content-type"), url, fallbackExt);
  const target = resolveKey(key);
  const partial = `${target}.part`;
  await mkdir(path.dirname(target), { recursive: true });

  let bytes = 0;
  const source = Readable.fromWeb(res.body as import("node:stream/web").ReadableStream);
  source.on("data", (chunk: Buffer) => {
    bytes += chunk.length;
    if (bytes > MAX_DOWNLOAD_BYTES) source.destroy(new Error("The generated file is larger than allowed"));
  });
  try {
    await pipeline(source, createWriteStream(partial));
    await rename(partial, target);
  } catch (e) {
    await rm(partial, { force: true });
    throw e;
  }
  return { key, bytes, mimeType: mimeFor(key) };
}

/**
 * Serves a stored file, honouring a single HTTP byte range so a <video> can
 * seek without downloading the whole clip.
 */
export async function serveFile(
  key: string,
  request: Request,
  opts: { downloadName?: string } = {},
): Promise<NextResponse> {
  let full: string;
  let size: number;
  try {
    full = resolveKey(key);
    size = (await stat(full)).size;
  } catch {
    return new NextResponse("Not found", { status: 404 });
  }

  const headers = new Headers({
    "Content-Type": mimeFor(key),
    "Accept-Ranges": "bytes",
    "Cache-Control": "private, max-age=3600",
    "X-Content-Type-Options": "nosniff",
  });
  if (opts.downloadName) {
    headers.set("Content-Disposition", `attachment; filename="${opts.downloadName.replace(/[^\w.-]+/g, "_")}"`);
  }

  const range = request.headers.get("range");
  const match = range ? /^bytes=(\d*)-(\d*)$/.exec(range.trim()) : null;
  if (match && (match[1] !== "" || match[2] !== "")) {
    let start: number;
    let end: number;
    if (match[1] === "") {
      // Suffix range: the last N bytes.
      const n = Number(match[2]);
      start = Math.max(0, size - n);
      end = size - 1;
    } else {
      start = Number(match[1]);
      end = match[2] === "" ? size - 1 : Math.min(Number(match[2]), size - 1);
    }
    if (start >= size || start > end) {
      headers.set("Content-Range", `bytes */${size}`);
      return new NextResponse(null, { status: 416, headers });
    }
    headers.set("Content-Range", `bytes ${start}-${end}/${size}`);
    headers.set("Content-Length", String(end - start + 1));
    const stream = Readable.toWeb(createReadStream(full, { start, end })) as ReadableStream;
    return new NextResponse(stream, { status: 206, headers });
  }

  headers.set("Content-Length", String(size));
  const stream = Readable.toWeb(createReadStream(full)) as ReadableStream;
  return new NextResponse(stream, { status: 200, headers });
}

/* ── Uploads from people (template packs, character images) ────────────── */

export const MAX_IMAGE_UPLOAD_BYTES = INPUT_IMAGE_LIMITS.maxBytes;

/** Width and height of image bytes, or null when they cannot be read as an image. */
export async function imageDimensions(bytes: Uint8Array): Promise<{ width: number; height: number } | null> {
  try {
    const { default: sharp } = await import("sharp");
    const m = await sharp(bytes).metadata();
    return m.width && m.height ? { width: m.width, height: m.height } : null;
  } catch {
    return null;
  }
}

/**
 * The bytes to send to the provider: the stored picture, scaled down when its long side is over
 * `sendMaxSide`. Returns the original untouched when it is already small enough.
 */
export async function bytesForProvider(key: string): Promise<{ bytes: Buffer; mimeType: "image/png" | "image/jpeg" | "image/webp" }> {
  const raw = await readFile(resolveKey(key));
  const kind = sniffImage(raw);
  if (!kind) throw new UploadError("That stored file is not an image.");
  const dims = await imageDimensions(raw);
  if (!dims) return { bytes: raw, mimeType: kind.mimeType };
  const target = sendSize(dims.width, dims.height);
  if (target.width === dims.width && target.height === dims.height) return { bytes: raw, mimeType: kind.mimeType };
  const { default: sharp } = await import("sharp");
  const resized = await sharp(raw).resize(target.width, target.height, { fit: "inside" }).toBuffer();
  return { bytes: resized, mimeType: kind.mimeType };
}

/** What an uploaded image really is, from its first bytes, never from its name or content-type. */
export function sniffImage(bytes: Uint8Array): { mimeType: "image/png" | "image/jpeg" | "image/webp"; ext: ".png" | ".jpg" | ".webp" } | null {
  if (bytes.length >= 8 && bytes[0] === 0x89 && bytes[1] === 0x50 && bytes[2] === 0x4e && bytes[3] === 0x47) return { mimeType: "image/png", ext: ".png" };
  if (bytes.length >= 3 && bytes[0] === 0xff && bytes[1] === 0xd8 && bytes[2] === 0xff) return { mimeType: "image/jpeg", ext: ".jpg" };
  if (
    bytes.length >= 12 &&
    String.fromCharCode(bytes[0]!, bytes[1]!, bytes[2]!, bytes[3]!) === "RIFF" &&
    String.fromCharCode(bytes[8]!, bytes[9]!, bytes[10]!, bytes[11]!) === "WEBP"
  ) {
    return { mimeType: "image/webp", ext: ".webp" };
  }
  return null;
}

export class UploadError extends Error {}

/** Documents a brand may keep alongside its pictures (style guides, price lists). */
export const DOCUMENT_EXTENSIONS = [".pdf", ".docx", ".xlsx", ".pptx"] as const;

/**
 * Stores a document upload. Only PDF and Office files, up to 10 MB, and the first bytes must
 * match the extension (a PDF starts "%PDF-", an Office file is a ZIP). Always served back as a download.
 */
export async function saveDocument(file: Blob & { name?: string }, keyWithoutExt: string): Promise<{ key: string; bytes: number; mimeType: string; ext: string }> {
  if (file.size === 0) throw new UploadError("That file is empty.");
  if (file.size > MAX_IMAGE_UPLOAD_BYTES) throw new UploadError(`Files can be at most ${MAX_IMAGE_UPLOAD_BYTES / 1024 / 1024} MB.`);
  const ext = path.extname(file.name ?? "").toLowerCase();
  if (!(DOCUMENT_EXTENSIONS as readonly string[]).includes(ext)) throw new UploadError("Upload a PDF, Word, Excel or PowerPoint file, or a picture.");
  const buf = new Uint8Array(await file.arrayBuffer());
  const isPdf = buf.length > 5 && String.fromCharCode(buf[0]!, buf[1]!, buf[2]!, buf[3]!, buf[4]!) === "%PDF-";
  const isZip = buf.length > 4 && buf[0] === 0x50 && buf[1] === 0x4b && buf[2] === 0x03 && buf[3] === 0x04;
  if (ext === ".pdf" ? !isPdf : !isZip) throw new UploadError("That file does not look like the type its name says.");
  const key = `${keyWithoutExt}${ext}`;
  const full = resolveKey(key);
  await mkdir(path.dirname(full), { recursive: true });
  const tmp = `${full}.part`;
  await writeFile(tmp, buf);
  await rename(tmp, full);
  return { key, bytes: buf.length, mimeType: MIME_BY_EXT[ext]!, ext };
}

/**
 * Stores an uploaded image under `keyWithoutExt` plus the extension its bytes
 * call for. Only PNG, JPEG and WebP up to 10 MB are accepted; anything else
 * (an SVG with script in it, an HTML file renamed .png) is refused.
 */
export async function saveUpload(file: Blob, keyWithoutExt: string): Promise<{ key: string; bytes: number; mimeType: string }> {
  if (file.size === 0) throw new UploadError("That file is empty.");
  if (file.size > MAX_IMAGE_UPLOAD_BYTES) throw new UploadError(`Images can be at most ${MAX_IMAGE_UPLOAD_BYTES / 1024 / 1024} MB.`);
  const buf = new Uint8Array(await file.arrayBuffer());
  const kind = sniffImage(buf);
  if (!kind) throw new UploadError("Upload a PNG, JPEG or WebP image.");
  const dims = await imageDimensions(buf);
  if (!dims) throw new UploadError("That image could not be read. Try saving it again as a PNG or JPEG.");
  const problem = imageSizeProblem(dims.width, dims.height);
  if (problem) throw new UploadError(problem);
  const key = `${keyWithoutExt}${kind.ext}`;
  const full = resolveKey(key);
  await mkdir(path.dirname(full), { recursive: true });
  const tmp = `${full}.part`;
  await writeFile(tmp, buf);
  await rename(tmp, full);
  return { key, bytes: buf.length, mimeType: kind.mimeType };
}

/** Copies a stored file to a new key (used to keep a generated image as a character). */
export async function copyStored(fromKey: string, keyWithoutExt: string): Promise<{ key: string; bytes: number; mimeType: string }> {
  const src = resolveKey(fromKey);
  const ext = path.extname(fromKey).toLowerCase() === ".jpeg" ? ".jpg" : path.extname(fromKey).toLowerCase();
  if (!MIME_BY_EXT[ext] || !MIME_BY_EXT[ext]!.startsWith("image/")) throw new UploadError("Only images can be kept as characters.");
  const key = `${keyWithoutExt}${ext}`;
  const dest = resolveKey(key);
  await mkdir(path.dirname(dest), { recursive: true });
  await copyFile(src, dest);
  return { key, bytes: (await stat(dest)).size, mimeType: MIME_BY_EXT[ext]! };
}

/** Removes a stored file; a missing file is fine. */
export async function removeStored(key: string): Promise<void> {
  try {
    await rm(resolveKey(key), { force: true });
  } catch {
    /* already gone */
  }
}

/** Reads the `file` fields of a multipart request, refusing oversized bodies before buffering them. */
export async function readUploads(request: Request, maxFiles: number): Promise<{ files: File[]; fields: Record<string, string> }> {
  const declared = Number(request.headers.get("content-length") ?? 0);
  if (declared > (MAX_IMAGE_UPLOAD_BYTES + 512 * 1024) * maxFiles) throw new UploadError("That upload is too large.");
  let form: FormData;
  try {
    form = await request.formData();
  } catch {
    throw new UploadError("Send the image as a form upload.");
  }
  const files: File[] = [];
  const fields: Record<string, string> = {};
  for (const [k, v] of form.entries()) {
    if (typeof v === "string") fields[k] = v;
    else files.push(v);
  }
  if (files.length === 0) throw new UploadError("Choose an image to upload.");
  if (files.length > maxFiles) throw new UploadError(`Upload at most ${maxFiles} image${maxFiles === 1 ? "" : "s"} at a time.`);
  return { files, fields };
}
