process.loadEnvFile('.env');
const { PrismaClient } = require('@prisma/client');
const db = new PrismaClient();
(async () => {
  const orgs = await db.organization.findMany();
  console.log('Organizations (' + orgs.length + '):');
  for (const o of orgs) console.log('  ' + o.name + ' (' + o.plan + ')');
  const brands = await db.brand.findMany();
  console.log('\nBrands (' + brands.length + '):');
  for (const b of brands) console.log('  ' + b.name + ' [' + b.slug + '] ' + b.brandNumber);
  const tasks = await db.contentTask.findMany({ orderBy: { taskNumber: 'asc' } });
  console.log('\nContent Tasks (' + tasks.length + '):');
  for (const t of tasks) console.log('  ' + t.taskNumber + ' ' + t.title + ' [' + t.contentType + '/' + t.status + ']');
  const channels = await db.socialChannel.findMany();
  console.log('\nSocial Channels (' + channels.length + '):');
  for (const c of channels) console.log('  ' + c.name + ' (' + c.platform + ': @' + c.handle + ')');
  const campaigns = await db.campaign.findMany();
  console.log('\nCampaigns (' + campaigns.length + '):');
  for (const c of campaigns) console.log('  ' + c.campaignNumber + ' ' + c.name + ' (KES ' + (c.budgetCents/100).toFixed(2) + ')');
  const items = await db.catalogueItem.findMany();
  console.log('\nCatalogue Items (' + items.length + '):');
  for (const i of items) console.log('  ' + i.name + ' (' + i.sku + ', KES ' + (i.priceCents/100).toFixed(2) + ')');
  const users = await db.user.findMany({ select: { email: true, name: true } });
  console.log('\nUsers (' + users.length + '):');
  for (const u of users) console.log('  ' + u.email + ' - ' + u.name);
  await db.$disconnect();
  console.log('\nDone.');
  process.exit(0);
})().catch(e => { console.error(e); process.exit(1); });
